# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/library/geometry.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/library/geometry.ipynb 3
from .criteria import * 
from .connections import * 
from .metrics import * 
from .manifolds import *
__all__ = ['PullbackMetric', 'RiemannianManifold', 'LeviCivitaConnection', 'plot_indicatrices', 'indicatrix_volume_variance_metric', 'frequency_of_volume_variance', 'curvature_matching_metric']
