# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/autometric',
                'doc_host': 'https://professorwug.github.io',
                'git_url': 'https://github.com/professorwug/autometric',
                'lib_path': 'autometric'},
  'syms': {'autometric.core': {'autometric.core.foo': ('core.html#foo', 'autometric/core.py')}}}
