# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/1 Geometer's Delight.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/1 Geometer's Delight.ipynb 3
from .n1d_embedding_analysis import *
from .connections import *
from .metrics import *
from .manifolds import *
